script: bundle exec rake spec

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.herokuapp.com/travis
